from __future__ import annotations
"This file was generated by Deepseek v4 pro"
"""
Live audio segmentation for faster-whisper processing.

Captures microphone input and yields speech segments detected via VAD,
with a fixed maximum-duration fallback to prevent unbounded segments.
"""

import threading
import time
from collections import deque
from collections.abc import Generator
from typing import Optional

import numpy as np
import sounddevice as sd
import webrtcvad


def live_audio_segments(
    sample_rate: int = 16000,
    vad_aggressiveness: int = 2,
    frame_duration_ms: int = 30,
    min_speech_duration_ms: int = 250,
    max_speech_duration_ms: int = 30_000,
    silence_duration_ms: int = 500,
    buffer_size_seconds: float = 60.0,
    device: Optional[int] = None,
) -> Generator[np.ndarray, None, None]:
    """
    Generator that captures live microphone audio and yields speech segments.

    Parameters
    ----------
    sample_rate : int
        Audio sample rate in Hz. Must be 8000, 16000, 24000, 32000, or 48000.
        When 24000 is used, VAD is performed on an internally-resampled 16000 Hz copy.
    vad_aggressiveness : int
        VAD aggressiveness (0-3). 0 = least aggressive, 3 = most.
    frame_duration_ms : int
        Frame size in ms for VAD. Must be 10, 20, or 30.
    min_speech_duration_ms : int
        Minimum speech duration to consider a valid utterance (ignores clicks/noise).
    max_speech_duration_ms : int
        Maximum speech duration before forcing a segment split (fallback).
    silence_duration_ms : int
        Consecutive silence duration needed to end a speech segment.
    buffer_size_seconds : float
        Size of the rolling audio buffer in seconds.
    device : Optional[int]
        Input device index. None selects the system default.

    Yields
    ------
    np.ndarray
        Float32 numpy array of shape (n_samples,) at the configured sample_rate,
        ready to be passed to a faster-whisper model.
    """
    segmenter = _AudioSegmenter(
        sample_rate=sample_rate,
        vad_aggressiveness=vad_aggressiveness,
        frame_duration_ms=frame_duration_ms,
        min_speech_duration_ms=min_speech_duration_ms,
        max_speech_duration_ms=max_speech_duration_ms,
        silence_duration_ms=silence_duration_ms,
        buffer_size_seconds=buffer_size_seconds,
        device=device,
    )

    try:
        segmenter.start()
        while True:
            segment = segmenter.get_segment()
            if segment is not None:
                yield segment
    finally:
        segmenter.stop()


class _AudioSegmenter:
    """Internal class managing audio capture, VAD, and state-machine logic."""

    def __init__(
        self,
        sample_rate: int,
        vad_aggressiveness: int,
        frame_duration_ms: int,
        min_speech_duration_ms: int,
        max_speech_duration_ms: int,
        silence_duration_ms: int,
        buffer_size_seconds: float,
        device: Optional[int],
    ) -> None:
        _VALID_RATES = (8000, 16000, 24000, 32000, 48000)
        if sample_rate not in _VALID_RATES:
            raise ValueError(f"sample_rate must be {', '.join(str(r) for r in _VALID_RATES)}; got {sample_rate}")
        if frame_duration_ms not in (10, 20, 30):
            raise ValueError(f"frame_duration_ms must be 10, 20, or 30; got {frame_duration_ms}")

        self._sample_rate = sample_rate
        # webrtcvad only natively supports 8/16/32/48 kHz; resample internally for 24 kHz
        if sample_rate == 24000:
            self._vad_sample_rate = 16000
        else:
            self._vad_sample_rate = sample_rate

        self._frame_duration_ms = frame_duration_ms
        self._frame_size = int(sample_rate * frame_duration_ms / 1000)  # samples per frame (native rate)
        self._vad_frame_size = int(self._vad_sample_rate * frame_duration_ms / 1000)  # samples per VAD frame
        self._buffer_size = int(sample_rate * buffer_size_seconds)

        self._min_speech_frames = max(1, min_speech_duration_ms // frame_duration_ms)
        self._max_speech_frames = max_speech_duration_ms // frame_duration_ms
        self._silence_frames = max(1, silence_duration_ms // frame_duration_ms)

        self._vad = webrtcvad.Vad(vad_aggressiveness)

        # Rolling buffer of all recent audio (numpy float32)
        self._buffer: deque[np.ndarray] = deque()
        self._buffer_sample_count: int = 0

        # Queue of complete segments ready for pickup
        self._segment_queue: deque[np.ndarray] = deque()

        # State machine
        self._speech_frame_count: int = 0
        self._silence_frame_count: int = 0
        self._in_speech: bool = False
        self._absolute_sample_index: int = 0  # total samples captured so far

        # Speech segment accumulator (avoids buffer-slicing bugs)
        self._speech_frames: list[np.ndarray] = []
        # Rolling pre-speech buffer for min_speech_frames lookback
        self._pre_speech_buffer: deque[np.ndarray] = deque(maxlen=self._min_speech_frames)

        self._stream: Optional[sd.InputStream] = None
        self._stop_event = threading.Event()
        self._lock = threading.Lock()

        self._device = device

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Open the input stream and begin capturing audio."""

        def _audio_callback(indata: np.ndarray, frames: int, time_info, status) -> None:
            if status:
                # Underflow/overflow warnings are non-fatal
                pass
            with self._lock:
                # Keep a flat float32 copy
                chunk = (indata.flatten().astype(np.float32) / 32768.0).copy()

                self._buffer.append(chunk)
                self._buffer_sample_count += len(chunk)
                # Trim buffer if it exceeds the configured size
                while self._buffer_sample_count > self._buffer_size and self._buffer:
                    dropped = self._buffer.popleft()
                    self._buffer_sample_count -= len(dropped)
                    self._absolute_sample_index += len(dropped)
                # Run VAD on the new frames
                self._process_vad_frames(chunk)
        print(sd.query_devices())
        self._stream = sd.InputStream(
            samplerate=self._sample_rate,
            channels=1,
            dtype="int16",  # webrtcvad requires 16-bit PCM
            blocksize=self._frame_size,
            device=self._device,
            callback=_audio_callback,
        )
        self._stream.start()

    def stop(self) -> None:
        """Close the stream and clean up."""
        if self._stream is not None:
            self._stream.stop()
            self._stream.close()
            self._stream = None

    def get_segment(self, timeout: float = 0.1) -> Optional[np.ndarray]:
        """
        Block until a complete segment is available or timeout expires.

        Returns
        -------
        np.ndarray or None
            A speech segment as float32 numpy array, or None if no segment is ready.
        """
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            with self._lock:
                if self._segment_queue:
                    return self._segment_queue.popleft()
            time.sleep(0.01)
        return None

    # ------------------------------------------------------------------
    # VAD state machine
    # ------------------------------------------------------------------

    def _process_vad_frames(self, chunk: np.ndarray) -> None:
        """Slice the incoming chunk into VAD-sized frames and advance the state machine."""
        # Resample to VAD rate if the native rate isn't natively supported by webrtcvad
        if self._sample_rate != self._vad_sample_rate:
            vad_chunk = self._resample(chunk, self._sample_rate, self._vad_sample_rate)
        else:
            vad_chunk = chunk

        num_native_frames = len(chunk) // self._frame_size
        num_vad_frames = len(vad_chunk) // self._vad_frame_size
        num_frames_in_chunk = min(num_native_frames, num_vad_frames)
        if num_frames_in_chunk == 0:
            return

        for i in range(num_frames_in_chunk):
            # Native-rate frame for storage / output
            nat_start = i * self._frame_size
            frame = chunk[nat_start : nat_start + self._frame_size].copy()

            # VAD-rate frame for speech classification
            vad_start = i * self._vad_frame_size
            vad_frame = vad_chunk[vad_start : vad_start + self._vad_frame_size]

            # Convert float32 → int16 for webrtcvad
            int16_frame = (vad_frame.clip(-1.0, 1.0) * 32767).astype(np.int16).tobytes()
            is_speech = self._vad.is_speech(int16_frame, self._vad_sample_rate)

            if is_speech:
                self._speech_frame_count += 1
                self._silence_frame_count = 0
                if not self._in_speech and self._speech_frame_count >= self._min_speech_frames:
                    # Transition: silence → speech
                    self._in_speech = True
                    # Prepend the pre-speech lookback frames into the accumulator
                    self._speech_frames = list(self._pre_speech_buffer) + self._speech_frames
                    self._pre_speech_buffer.clear()
                self._speech_frames.append(frame)
            else:
                self._silence_frame_count += 1
                # Always keep the last N frames for potential speech lookback
                self._pre_speech_buffer.append(frame)
                if self._in_speech:
                    # Still add silence frames during speech (they're part of the segment)
                    self._speech_frames.append(frame)
                    # Check if we've reached max duration → force segment end
                    total_speech_frames = self._speech_frame_count
                    if total_speech_frames >= self._max_speech_frames:
                        self._emit_segment()
                    elif self._silence_frame_count >= self._silence_frames:
                        self._emit_segment()
                else:
                    # Not in speech yet; reset speech counter if silence
                    self._speech_frame_count = 0
                    self._speech_frames.clear()

    def _emit_segment(self) -> None:
        """Extract the current utterance from the accumulator and queue it."""
        if not self._in_speech:
            return

        frames = self._speech_frames
        self._speech_frames = []

        if not frames:
            self._reset_state()
            return

        segment = np.concatenate(frames)

        if len(segment) > 0:
            self._segment_queue.append(segment)

        self._reset_state()

    def _resample(self, data: np.ndarray, orig_sr: int, target_sr: int) -> np.ndarray:
        """Resample audio data to a target sample rate using linear interpolation."""
        duration = len(data) / orig_sr
        new_length = int(round(duration * target_sr))
        x_orig = np.arange(len(data), dtype=np.float64)
        x_new = np.linspace(0.0, float(len(data) - 1), new_length, dtype=np.float64)
        return np.interp(x_new, x_orig, data).astype(np.float32)

    def _reset_state(self) -> None:
        """Clear speech-tracking state after a segment is emitted."""
        self._in_speech = False
        self._speech_frame_count = 0
        self._silence_frame_count = 0
        self._speech_frames.clear()
        self._pre_speech_buffer.clear()
